name: Task
description: シンプルなタスク用Issueテンプレート
title: "[Task]: "
labels: ["task"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📌 タスク内容を記入してください。

  - type: textarea
    id: details
    attributes:
      label: 詳細説明
      description: タスクの具体的な内容を記入してください。
      placeholder: "ここにタスクの詳細を記入..."
    validations:
      required: true
